### PR TITLE
doc: Architecture diagrams updated with ChargeMessage persistence

### PR DESCRIPTION
**Pull request by HenrikSommer**
## Description

Architecture diagrams are updated to reflect changes in pull request 1803

## References

* #1689

### CODE REVIEW

**Review by prtandrup — COMMENTED** [review]
I think the ChargePrices.png has been stored in the wrong file name ChargeAndChargePrices?
Additionally, there is an arrow going from the message persister to the integration event publisher, unintended?

**Review by x-platformcoder — COMMENTED** [review]
minor: maybe we should rename ARCHITECTURE-ChargeAndChargePrices.png to ARCHITECTURE-ChargePrices.png

**Review by x-platformcoder — COMMENTED** [review]
missing arrow on connectors for chargemessage DB

**Review by x-platformcoder — COMMENTED** [review]
why the connector from chargepricemessagepersister to chargepriceintegrationpublisher?

**Review by prtandrup — APPROVED** [review]

**Pull request merged**
