### PR TITLE
added Terraform CI

### PR DESCRIPTION
**Pull request by Renetnielsen**
## Description

The goal of this PR is to have a temporary private environment being spun up per PR in order to later be able to do various kinds of testing and QA before entering main.

Aside from the code an environment `rg-DataHub-Testing-U` has been created and configured with secrets.

## References

* #167

### CODE REVIEW

**Comment by BjarkeMeier** [comment]
Thank you very much for your contribution @Renetnielsen. Per team decision I however change status to draft as we currently have decided to postpone implementing integration tests on PR environment. But we still want to keep your PR to eventually activate/merge it later.

**Comment by Mech0z** [comment]
> 
> 
> @Mech0z, why did you reopen this PR? It creates noise in the PR overview, so I believe it would be best to close it. But we definitely will want to keep in mind that we have this PR in stock.

Because it was closed by @PerLysemose due to a Zenhub error and I am not sure @Renetnielsen would notice

**Comment by BjarkeMeier** [comment]
Ok. But I'll close it then. @Renetnielsen knows that we are not implementing this at the moment but will likely activate it later.

**Comment by BjarkeMeier** [comment]
We have decided to try out this approach.

**Comment by HenrikSommer** [comment]
PR #368 is opened and replaces this PR

**Pull request closed without merging**
